"""vn_wards

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-06 16:02:27.759732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vn_wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('province_code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('full_name_en', sa.String(length=150), nullable=False),
    sa.Column('code_name', sa.String(length=100), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vn_wards')),
    sa.UniqueConstraint('code', name=op.f('uq_vn_wards_code'))
    )
    with op.batch_alter_table('vn_wards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vn_wards_province_code'), ['province_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vn_wards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vn_wards_province_code'))

    op.drop_table('vn_wards')
    # ### end Alembic commands ###
